spring :
  jpa :
    show-sql : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.cache.use_second_level_cache : false
      hibernate.cache.use_query_cache : false
      hibernate.generate_statistics : true
      hibernate.format_sql : true
  devtools :
    add-properties : true
    restart :
      enabled : true
    livereload :
      enabled : true
management :
  endpoints :
    enabled-by-default : true

springdoc :
  show-actuator : true
