version : '3'
services :
  postgres :
    image : "postgres:13.9"
    container_name : ${artifactId}-dev-postgres
    restart : unless-stopped
    ports :
      - "5432:5432"
    environment :
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=svc_testing_db
  prometheus :
    container_name : ${artifactId}-dev-prometheus
    image : prom/prometheus:v2.42.0
    volumes :
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : ${artifactId}-dev-grafana
    image : grafana/grafana:9.3.6
    volumes :
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
